WIP: Avoid count request stuff
hiqdev/hipanel-core pull request #145
Opened 2020-11-06 15:32 UTC by tafid

2020-11-09 12:50 UTC, SilverFire requested changes

2020-11-09 12:50 UTC, SilverFire commented on src/messages/ru/hipanel.php
> +    'loading pager...' => 'загружаю пагинацию...',
```suggestion
    'loading pager...' => 'загружаю старницы...',
```

2020-11-09 12:50 UTC, SilverFire commented on src/messages/ru/hipanel.php
> +    'loading summary...' => 'загружаю самари...',
```suggestion
    'loading summary...' => 'загружаю итог...',
```

2020-11-09 12:50 UTC, SilverFire commented on src/actions/IndexAction.php
> +
Нужен PHPDoc

2020-11-09 12:50 UTC, SilverFire commented on src/actions/IndexAction.php
> +                    'pager' => fn(VariantsAction $action): string => SynchronouslyCountEnabler::widget([
Учитывая, что `pager` – это ключевое слово, и ты на него ссылаешься из других классов, предлагаю сделать это публичной константой: так будет проще навигация по коду

2020-11-09 12:50 UTC, SilverFire commented on src/actions/VariantsAction.php
> +        $headerName = $this->controller->request->headers->get(self::EXPECTED_AJAX_RESPONSE_HEADER_NAME);
```suggestion
        $headerValue = $this->controller->request->headers->get(self::EXPECTED_AJAX_RESPONSE_HEADER_NAME);
```

Там же по идее знаечние заголовка, а не его имя

2020-11-09 12:50 UTC, SilverFire commented on src/actions/VariantsAction.php
> +        foreach ($this->variants as $expected => $variant) {
Можно проще

```suggestion
        if (isset($this->variants[$headerName])) {
            return $this->variants[$headerName]($this);
        }
```

2020-11-09 12:50 UTC, SilverFire commented on src/actions/VariantsAction.php
> +    public array $variants;
Тип переменной `array`, но в конструкторе нет обязательной инициализации. Потенциальный `Fatal`
```suggestion
    public array $variants = [];
```

```suggestion
    public ?array $variants = null;
```

2020-11-09 12:50 UTC, SilverFire commented on src/actions/VariantsAction.php
> +    public function init()
Можно удалить как неиспользуемый

2020-11-09 12:50 UTC, SilverFire commented on src/widgets/SynchronouslyCountEnabler.php
> +class SynchronouslyCountEnabler extends Widget
```suggestion
class SynchronousCountEnabler extends Widget
```

2020-11-11 14:27 UTC, hiqsol approved these changes

2020-11-11 14:38 UTC, hiqsol approved these changes

2020-11-11 14:38 UTC, merged