fix php notice
hiqdev/hipanel-core pull request #151
Opened 2021-03-11 08:12 UTC by bladeroot

2021-03-11 12:49 UTC, SilverFire commented on src/helpers/SellerHelper.php
> +    public static function get() : string
```suggestion
    public static function getLogin(): string
```

Как насчёт более явного имени?

2021-03-11 12:51 UTC, hiqsol requested changes

2021-03-11 12:51 UTC, hiqsol commented on src/helpers/SellerHelper.php
> +    public static function get() : string
поддерживаю

2021-03-11 16:08 UTC, SilverFire commented on src/helpers/UserHelper.php
> +        $sellerModel = Client::perform('check', [
Как насчёт закешировать?

2021-03-12 11:28 UTC, hiqsol approved these changes

2021-03-12 11:30 UTC, SilverFire approved these changes

2021-03-12 11:30 UTC, merged