LocalHipanel.md Edit
hiqdev/hipanel-core pull request #168
Opened 2021-05-19 09:06 UTC by Drakorgaur

2021-05-19 09:40 UTC, hiqsol commented on docs/LocalHipanel.md
> +- Docker install ```$ sudo apt install docker```
```suggestion
- Docker install ```sudo apt install docker```
```

2021-05-19 09:42 UTC, hiqsol requested changes

2021-05-19 09:42 UTC, hiqsol commented on docs/LocalHipanel.md
> -4. `hidev up`
@strorch а чё решили убрать `hidev up`? не работает?
он делает несколько полезных вещей: симлинки, права на runtime и assets

2021-05-19 11:41 UTC, strorch requested changes

2021-05-19 11:41 UTC, strorch commented on docs/LocalHipanel.md
> +- Nginx Proxy Server install ```sudo apt-get install nginx```
а оце навіщо? проксі треба з hiqdev/nginx-proxy-common

2021-05-19 11:41 UTC, strorch commented on docs/LocalHipanel.md
> +- Composer install ```sudo apt install composer```
композер не так ставиться

2021-05-19 11:41 UTC, strorch commented on docs/LocalHipanel.md
> -4. `hidev up`
ну з коробки це не працює

```
-> % ./vendor/bin/hidev up
Dir:hipanel.demo.hipanel.com and Host:hipanel-demo.hipanel.com doesn't match
```

а сімлінки на `core` уже є, а про права треба @Drakorgaur щоб окремими пунктами написав бо це не очевидно

2021-05-19 11:41 UTC, strorch commented on docs/LocalHipanel.md
> -4. `hidev up`
так всеодно не працює
```
--- a/hidev.yml
+++ b/hidev.yml
@@ -1,6 +1,6 @@
 package:
     type:           project
-    name:           hipanel-demo.hipanel.com
+    name:           hipanel.demo.hipanel.com
```

2021-05-19 11:41 UTC, strorch commented on docs/LocalHipanel.md
> +- PHP install ```sudo apt install php7.4```
і допиши щоб поставить усі екстеншни для пхп

2021-05-19 11:41 UTC, strorch commented on docs/LocalHipanel.md
> +- Nginx Proxy Server start ```sudo systemctl start nginx```
також не треба

2021-05-20 10:24 UTC, strorch requested changes
пофікси ще пліз отут не співпадають назви папок 

https://github.com/hiqdev/hipanel-core/blob/master/docs/LocalHipanel.md#recommended-dirs

2021-05-20 10:24 UTC, strorch commented on docs/LocalHipanel.md
> +- Nginx Proxy Server install from hiqdev/nginx-proxy-common
цей пункт не відноситься до сетапа серидовища, він написаний і написаний в пункті `Installation`

2021-05-20 10:24 UTC, strorch commented on docs/LocalHipanel.md
> +chmod 777 .docker-compose.yml
цього непотрібно робить, права треба врегулювать тільки для `runtime & public/assets`, про це написано вище

2021-05-21 21:16 UTC, hiqsol approved these changes

2021-05-21 21:18 UTC, merged