Grid edit
hiqdev/hipanel-core pull request #172
Opened 2021-05-28 07:23 UTC by Drakorgaur

New Methods for Finance -> CopyBill

2021-06-01 12:04 UTC, strorch requested changes

2021-06-01 12:04 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +        for($columnNumber = 2; $columnNumber <= 10; $columnNumber++)
```suggestion
        foreach (range(2, 10) as $columnNumber) {
```

2021-06-01 12:04 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +    public function ensureBillViewContainsData($element): void
```suggestion
    public function ensureBillViewContainsData(array $elements): void
```

2021-06-01 12:04 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +        foreach($element as $tableContent){
```suggestion
        foreach($element as $tableContent) {
```

2021-06-01 12:04 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +        {
треба тут кодстайл по PSR повирівнювать

2021-06-01 12:04 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +    public function getColumnNumber($columnName)
```suggestion
    public function getColumnNumber(string $columnName): string
```

2021-06-01 12:04 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +    public function ensureChargeViewContainsData($chargeData): void
```suggestion
    public function ensureChargeViewContainsData(array $chargeData): void
```

2021-06-01 12:04 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +    public function ensureBillViewDontContainData($element): void
```suggestion
    public function ensureBillViewDontContainData(array $elements): void
```

2021-06-05 08:58 UTC, strorch requested changes

2021-06-05 08:58 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +   {
криві таби )

2021-06-05 08:58 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +       return $columnNumber;
неправильна функція, по-перше зроби через foreach, по-друге якщо ввести ім*я колонки якої немає, то верне неправильне число а не викине похибку

2021-06-05 08:58 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +    public function ensureBillViewContainsData(array $elements): void
ця функція не має тут буть, їх треба перенести в фінанс модуль

2021-06-05 08:58 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +    public function ensureChargeViewContainsData(array $chargeData): void
ця функція не має тут буть, їх треба перенести в фінанс модуль

2021-06-05 08:58 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +    public function ensureBillViewDontContainData(array $element): void
ця функція не має тут буть, їх треба перенести в фінанс модуль

2021-06-07 07:18 UTC, Drakorgaur commented on tests/_support/Page/Widget/Grid.php
> +       return $columnNumber;
1) А как мне делать через foreach, если я в функцию заношу не массив, а стринг с названием колонки?

2) ексепшн такой сделал, пойдет?

2021-06-10 16:21 UTC, strorch requested changes

2021-06-10 16:21 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +   public function ensureBillViewDontContainData($billData)
dont contain чи contain?

2021-06-10 16:21 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +   public function ensureBillViewDontContainData($billData)
```suggestion
   public function ensureBillViewDontContainData($billData): void
```

2021-06-10 16:21 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +    throw new \Exception("failed detect column with name $columnName");
таби попливли, поправ щоб редактор твій показував коректно

2021-06-10 16:21 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +    public function ensureSeeValueInColumn($columnNumber, $tableValue): void
```suggestion
    public function ensureSeeValueInColumn(string $columnNumber, string $tableValue): void
```

2021-06-10 16:21 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +        $I = $this->tester;
оце робить не обов*язково, якшо змінна 1 раз використовується

2021-06-10 16:21 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +            if($columnName == $currentColummName) {
```suggestion
            if($columnName === $currentColummName) {
```
почитай про різницю в пхп `==` і `===`

2021-06-11 06:36 UTC, strorch requested changes

2021-06-11 06:36 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +
```suggestion
```

2021-06-11 06:36 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +    public function ensureBillViewContainData($billData): void
```suggestion
    public function ensureBillViewContainData(array $billData): void
```

2021-06-14 10:26 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +    public function ensureSeeValueInColumn(string $columnNumber,string $tableValue): void
```suggestion
    public function ensureSeeValueInColumn(string $columnNumber, string $tableValue): void
```

2021-06-14 10:26 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +    throw new \Exception("failed detect column with name $columnName");
```suggestion
       throw new \Exception("failed detect column with name $columnName");
```

2021-06-14 10:27 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +       throw new \Exception("failed detect column with name $columnName");
```suggestion
        throw new \Exception("failed detect column with name $columnName");
```

2021-06-14 10:28 UTC, strorch approved these changes

2021-06-14 10:29 UTC, merged