Updated IndexPage for ClientExport in Client
hiqdev/hipanel-core pull request #176
Opened 2021-06-04 13:41 UTC by Drakorgaur

2021-06-04 13:44 UTC, Drakorgaur commented
https://github.com/hiqdev/hipanel-module-client/pull/146 - ClientExport

2021-06-15 07:57 UTC, strorch requested changes

2021-06-15 07:57 UTC, strorch commented on tests/_support/Page/IndexPage.php
> +        $keyName = key($option);
оце жесть, краще хай ім*я буде одним параметром функції, а іншим - масів значень

2021-06-15 07:57 UTC, strorch commented on tests/_support/Page/IndexPage.php
> +            $I->seeElement("//ul//li//a[contains(text(),'$element')]");
```suggestion
            $I->seeElement("//ul//li//a[contains(text(), '$element')]");
```

2021-06-23 05:22 UTC, Drakorgaur commented
дубль 182го

2021-06-23 05:22 UTC, closed without merging