Update MultipleSelect2, IndexPage and Grid for Filter test
hiqdev/hipanel-core pull request #187
Opened 2021-07-02 12:58 UTC by Drakorgaur

https://github.com/hiqdev/hipanel-module-finance/pull/271

2021-07-06 07:17 UTC, strorch requested changes

2021-07-06 07:17 UTC, strorch commented on tests/_support/Page/IndexPage.php
> +    public function setAdvancedFilter(TestableInput $filter, $value): void
тайпхінт

2021-07-06 07:17 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +    public function setAdvancedFilter(TestableInput $filter, $value): void
тайпхінт

2021-07-06 07:17 UTC, strorch commented on tests/_support/Page/Widget/Input/MultipleSelect2.php
> +    private $inputSelector;
```suggestion
    private $inputSelector;

```

2021-07-06 07:17 UTC, strorch commented on tests/_support/Page/Widget/Input/MultipleSelect2.php
> +        $this->tester->pressKey($this->inputSelector, WebDriverKeys::ENTER);
а чого для того щоб закрить треба нажать ENTER?

2021-07-06 09:13 UTC, Drakorgaur commented on tests/_support/Page/Widget/Input/MultipleSelect2.php
> +        $this->tester->pressKey($this->inputSelector, WebDriverKeys::ENTER);
![image](https://user-images.githubusercontent.com/83531949/124574548-3e12bf80-de53-11eb-8029-054b92825d94.png)
![image](https://user-images.githubusercontent.com/83531949/124574747-74e8d580-de53-11eb-9777-cdfb817df12f.png)

у меня прост МультиплСелект работает с энтером, а не с кликом по селектору :/

2021-07-06 09:14 UTC, Drakorgaur commented on tests/_support/Page/Widget/Input/MultipleSelect2.php
> +        $this->tester->pressKey($this->inputSelector, WebDriverKeys::ENTER);
Эт не закрыть, а выбрать, :/

2021-07-06 09:15 UTC, Drakorgaur commented on tests/_support/Page/Widget/Input/MultipleSelect2.php
> +        $this->tester->pressKey($this->inputSelector, WebDriverKeys::ENTER);
прост в нормальных Селект2, когда выбираешь элемент - то окошко закрывается, а в мультипл - выбираешь, и можно дальше кликать по элементам, и эт не закроет окно, а для выхода - тут нажимается ESCAPE

2021-07-07 07:26 UTC, strorch approved these changes

2021-07-07 07:27 UTC, merged