Added methods for test - SaleAction
hiqdev/hipanel-core pull request #202
Opened 2021-09-06 08:07 UTC by Drakorgaur

2021-09-07 08:55 UTC, strorch requested changes

2021-09-07 08:55 UTC, strorch commented on tests/_support/Step/Acceptance/Client.php
> +        $I->click("//a[contains(text(),'Sign out')]");
```suggestion
        $I->clickLink('Sign out');
```

2021-09-07 08:55 UTC, strorch commented on tests/_support/Step/Acceptance/Client.php
> +        $I->click("//header//ul[1]/li[4]/a[1]");
а можна якось більш явно описать, що саме тут нажимається?

2021-09-07 08:55 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +    public function getRowNumberInColumnByValue(int $column, string $rowValue): int
```suggestion
    public function getRowNumberInColumnByValue(string $columnName, string $rowValue): int
```
ти коли використовуєш це писав `$col = $index->gridView->getColumnNumber()`
пропоную пошук айді колонки засунуть сюда

2021-09-08 07:50 UTC, Drakorgaur commented on tests/_support/Page/Widget/Grid.php
> +    public function getRowNumberInColumnByValue(int $column, string $rowValue): int
колонка не имеет айди жеж? или ты имеешь ввиду название колонки?

2021-09-09 07:33 UTC, strorch approved these changes

2021-09-09 07:33 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +            if($rowValue === $currentRow) {
```suggestion
            if ($rowValue === $currentRow) {
```

2021-09-09 07:33 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +        throw new \Exception("failed detect column with name $rowValue");
```suggestion
        throw new \Exception("Failed detect column with name $rowValue");
```

2021-09-09 07:33 UTC, merged