new methods
hiqdev/hipanel-core pull request #203
Opened 2021-09-09 10:01 UTC by Drakorgaur

2021-09-15 09:31 UTC, strorch requested changes

2021-09-15 09:31 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> +        throw new \Exception("failed detect row with name $rowValue");
```suggestion
        throw new \Exception("Failed detect column with name $rowValue");
```

2021-09-15 09:31 UTC, strorch commented on tests/_support/Page/Widget/Grid.php
> -    public function countColumnInTableBody(): int
цей метод вже видалився в #204

2021-09-16 06:41 UTC, Drakorgaur commented on tests/_support/Page/Widget/Grid.php
> +        throw new \Exception("failed detect row with name $rowValue");
тут именно row - метод называется getRowNumberInColumnByValue. Метод вызывает другой - getColumnNumber, который уже поднимит эксепшн, что нет колонки
![photo_2021-09-16_09-40-54](https://user-images.githubusercontent.com/83531949/133562670-f657ea31-bc73-4afa-b547-94c1b868fce5.jpg)

2021-09-17 11:00 UTC, strorch approved these changes

2021-09-17 11:01 UTC, merged