HP-1280 Attributes(volume_type, datacenter_ids) are incorrectly displ…
hiqdev/hipanel-core pull request #251
Opened 2023-03-10 09:39 UTC by gadezist

…ayed in plans

2023-03-10 17:58 UTC, tafid requested changes

2023-03-10 17:58 UTC, tafid commented on src/models/CustomAttribute.php
> +        } else if (array_is_list($this->value) && count($this->value) > 0) {
а зачем нужен else?

2023-03-13 11:36 UTC, SilverFire commented on src/widgets/CustomAttributesViewer.php
> +                    'format' => 'raw',
Now we have a persistent XSS here. Please, add proper escaping to the output.

2023-03-13 11:51 UTC, gadezist commented on src/models/CustomAttribute.php
> +        } else if (array_is_list($this->value) && count($this->value) > 0) {
Я перевіряю чи цей масив є списком і вивожу дані трохи інакше, тільки значення в стовпчик

2023-03-13 14:31 UTC, SilverFire commented on src/widgets/CustomAttributesViewer.php
> +                    'format' => 'html',
Use explicit `Html::encode` on values that you output.
`format => html` is a sanitizer for untrusted user input: it consumes a lot of resources compared to encoding

2023-03-14 12:09 UTC, merged