HP-1591: use internal tags
hiqdev/hipanel-core pull request #268
Opened 2023-09-21 15:13 UTC by bladeroot

2023-09-25 09:26 UTC, SilverFire requested changes

2023-09-25 09:26 UTC, SilverFire commented on src/behaviors/TaggableBehavior.php
> +        };
```suggestion
        if ($this->owner instanceof hipanel\modules\client\models\Client) {
            return !$user->can('client.update');
        }
```

Используй явно типы, это упрощает потом поиск мест использования и рефакторинг.
А вообще это ломает направление зависимостей. Модуль `hipanel-core` не зависит от модуля `hipanel-module-client`

2023-09-25 09:26 UTC, SilverFire commented on src/widgets/TagsManager.php
> +class TagsManager extends TagsClient
Я не сильно понимаю, зачем тут было выбрано наследование, учитывая предыдущий комментарий.

2023-09-25 09:26 UTC, SilverFire commented on src/widgets/TagsClient.php
> +        }
Я бы это не показывал в режиме read-only: все равно это никак не получится изменить тому, кто видит.

2023-09-25 11:20 UTC, tafid requested changes

2023-09-25 11:20 UTC, tafid commented on src/widgets/TagsManager.php
> +class TagsManager extends TagsClient
согласен

2023-09-25 18:38 UTC, bladeroot commented on src/widgets/TagsClient.php
> +        }
Потому что в таком исполнении используется в TagsManager . Или надо было дублировать полностью код?

2023-10-24 08:48 UTC, SilverFire approved these changes

2023-10-24 09:00 UTC, SilverFire requested changes

2023-10-24 09:00 UTC, SilverFire commented on src/widgets/TagsClient.php
> +class TagsClient extends Widget
```suggestion
class TagsReadOnly extends Widget
```

2023-11-01 10:08 UTC, SilverFire approved these changes

2023-11-01 10:09 UTC, merged